### ISSUE TITLE
Hello， when I clicked the close button of Sales Notification, it dont appear again

### ISSUE THREAD

**Issue by li2020rich** [WPDevelopers/notificationx#110]
Hi support team, it didn't pop up again until I clicked the close button. You told me before that it will appear again after 24 hours, but it never appears on my side. Is it my problem? Thanks

**Comment by arrasel13** [comment]
Hi @li2020rich

Hope you are doing well. Sorry for the inconvenience caused.
Generally, if you close any notification then it will appear again after 24 hours because the browser session or cookies or cache will be destroyed and it will appear again.

In your case, it seems your browser session or cookies or cache weren't destroyed and that's why it is not showing again. Once you check using the browser incognito mode or a new browser, you will get the notification again. You can try on browser incognito mode or a new browser, hope this will work properly.

So don't worry about it. This is a browser caching-related issue. For a better understanding, you can check this [screencast](https://d.pr/v/SLH59q).

However, I will discuss this with our Dev team, and we will try to improve this caching-related issue in our future version plugin, don't worry.

Hope this will help you. Let us know if you have any other queries.

Have a good day!

**Comment by li2020rich** [comment]
Hello, thank you very much for your reply, Now I know how it works.

**Comment by arrasel13** [comment]
Hi @li2020rich

Welcome and have a good day!
